In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
class Dense_layer():
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.1 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
        
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

In [3]:
class ReLU():
    def forward(self, inputs):
        self.output = np.maximum(0,inputs)

In [13]:
class softmax():
    def forward(self, inputs):
        exp_vals = np.exp(inputs - np.max(inputs, axis = 1, keepdims = True))
        probabilties = exp_vals / np.sum(exp_vals, axis = 1, keepdims = True)
        self.output = probabilties

In [17]:
class loss():
    def calculate(self, output, y):
        sample_losses = self.forward(output, y)
        data_loss = np.mean(sample_losses)
        return data_loss
class loss_CategoricalCrossEntropy(loss):
    def forward(self, y_pred, y_true):
        samples = len(y_pred)
        clipped = np.clip(y_pred, 1e-7, 1-1e-7)
        
        if len(y_true.shape) == 1:
            correct_confidences = clipped[range(samples), y_true]
        else:
            correct_confidences = np.sum(clipped * y_true, axis = 1)
        neg_log_liklihood = -np.log(correct_confidences)
        return neg_log_liklihood

In [7]:
def spiral_data(points, classes):
    X = np.zeros((points*classes, 2))
    y = np.zeros(points*classes, dtype='uint8')
    for class_number in range(classes):
        ix = range(points*class_number, points*(class_number+1))
        r = np.linspace(0.0, 1, points)  # radius
        t = np.linspace(class_number*4, (class_number+1)*4, points) + np.random.randn(points)*0.2
        X[ix] = np.c_[r*np.sin(t*2.5), r*np.cos(t*2.5)]
        y[ix] = class_number
    return X, y

In [25]:
X, y = spiral_data(points = 100, classes = 3)

In [26]:
dense1 = Dense_layer(2, 3)
activation1 = ReLU()
dense2 = Dense_layer(3, 3)
activation2 = softmax()
dense1.forward(X)
activation1.forward(dense1.output)
dense2.forward(activation1.output)
activation2.forward(dense2.output)
print(activation2.output[:5])

loss_func = loss_CategoricalCrossEntropy()
loss = loss_func.calculate(activation2.output, y)
predictions = np.argmax(activation2.output, axis = 1)
predictions

[[0.33333333 0.33333333 0.33333333]
 [0.33335122 0.33332618 0.33332259]
 [0.33337966 0.33331496 0.33330538]
 [0.33340571 0.33330467 0.33328962]
 [0.33343108 0.33329464 0.33327428]]


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0,
       0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 0, 2, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 2, 0, 2, 2,
       2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 0, 2,
       2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 0, 0,
       2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       2, 0, 0, 0, 0, 0, 2, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 2, 2], d

In [27]:
np.mean(predictions == y)

0.37333333333333335